<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><span class="aw-raf-statistics">
    <div class="fieldset">  
        <h2 class="legend"><?php echo $this->__('Social Share'); ?></h2>
        <!-- Twitter Button -->
        <div class="awraf-social-share">
            <a class="raf-twitter-share" target="_blank" href="https://twitter.com/home?status=<?php echo $this->getRefUrl(); ?>" title="<?php echo $this->__('Share on Twitter'); ?>"></a>
            <a class="raf-facebook-share" target="_blank" href="https://www.facebook.com/share.php?u=<?php echo $this->getRefUrl(); ?>" title="<?php echo $this->__('Share on Facebook'); ?>"></a>
            <a class="raf-myspace-share" target="_blank" href=" http://www.myspace.com/Modules/PostTo/Pages/?u=<?php echo $this->getRefUrl(); ?>" title="<?php echo $this->__('Share on MySpace'); ?>"></a>
        </div>   
    </div> 
</span>
